name: big_tip
description: Display information to the user using a custom layout, that can be actionable
version: 1.0.0
author: Jesus Rodriguez <jesusrope98@outlook.com>
homepage: https://github.com/jesusrp98/big_tip

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
