name: big_tip
description: Display information to the user using a custom layout, that can be actionable
version: 2.0.0
homepage: https://github.com/jesusrp98/big_tip

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
