name: big_tip
description: Display information to the user using a custom layout, that can be actionable
version: 1.1.0
homepage: https://github.com/jesusrp98/big_tip

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
